# Copyright (c) Datalayer, Inc. https://datalayer.io
# Distributed under the terms of the MIT License.

name: datalayer
channels:
  - conda-forge
dependencies:
  - jq
  - make
  - nodejs=18.17.1
  - pip
  - python=3.11
  - yarn=3.5.0
  - build
  - hatch
  - jupyterlab==4.0.3
